services:
  ocr_service:
    build: .
    ports:
      - "8082:8082"
    volumes:
      - ../data_shared:/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
  ocr_service_cpu:
    build: .
    ports:
      - "8082:8082"
    volumes:
      - ../data_shared:/data